stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw
  
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/data_preprocessing.py
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
      - src/feature_engineering.py
    outs:
      - data/features

  model_building:
    cmd: python src/model_building.py
    deps:
      - data/features/train_bow.csv
      - data/features/test_bow.csv
      - src/model_building.py
    outs:
      - model.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - model.pkl
      - src/model_evaluation.py
    metrics:
      - metrics.json